from __future__ import annotations

"""Thin re-export facade for apps.pdf public API (backward compatibility)."""

from apps.pdf.dates import (
    _parse_date,
    format_print_date,
    format_print_stamp,
    parse_date,
)
from apps.pdf.layout import (
    BASE_AFTER_GROUP_SPACE_BEFORE,
    BASE_CONTINUATION_LEADING,
    BASE_DISH_SPACE_BEFORE,
    BASE_GROUP_FONT_SIZE,
    BASE_GROUP_LEADING,
    BASE_GROUP_SPACE_BEFORE,
    BASE_MENU_FONT_SIZE,
    BASE_MENU_LEADING,
    MIN_MENU_FONT_SIZE,
    PAGE_CONTENT_BOTTOM,
    PAGE_CONTENT_TOP_OFFSET,
    PAGE_FOOTER_Y,
    PAGE_MARGIN_LEFT,
    PAGE_MARGIN_RIGHT,
    SPACING_SCALE_STEPS,
    PageLayout,
    TextBlock,
    compute_page_layout,
    enrich_page_items,
)
from apps.pdf.names import (
    FOOTER_NOTE_EN,
    FOOTER_NOTE_RU,
    UNKNOWN_LOCATION_LABEL,
    build_download_filename,
    resolve_cover_location,
)
from apps.pdf.render import (
    FONT_BOLD,
    FONT_CANDIDATES,
    FONT_REGULAR,
    FOOTER_FONT_SIZE,
    build_menu_pdf,
    get_menu_fonts,
)

__all__ = [
    "BASE_AFTER_GROUP_SPACE_BEFORE",
    "BASE_CONTINUATION_LEADING",
    "BASE_DISH_SPACE_BEFORE",
    "BASE_GROUP_FONT_SIZE",
    "BASE_GROUP_LEADING",
    "BASE_GROUP_SPACE_BEFORE",
    "BASE_MENU_FONT_SIZE",
    "BASE_MENU_LEADING",
    "FONT_BOLD",
    "FONT_CANDIDATES",
    "FONT_REGULAR",
    "FOOTER_FONT_SIZE",
    "FOOTER_NOTE_EN",
    "FOOTER_NOTE_RU",
    "MIN_MENU_FONT_SIZE",
    "PAGE_CONTENT_BOTTOM",
    "PAGE_CONTENT_TOP_OFFSET",
    "PAGE_FOOTER_Y",
    "PAGE_MARGIN_LEFT",
    "PAGE_MARGIN_RIGHT",
    "PageLayout",
    "SPACING_SCALE_STEPS",
    "TextBlock",
    "UNKNOWN_LOCATION_LABEL",
    "_parse_date",
    "build_download_filename",
    "build_menu_pdf",
    "compute_page_layout",
    "enrich_page_items",
    "format_print_date",
    "format_print_stamp",
    "get_menu_fonts",
    "parse_date",
    "resolve_cover_location",
]
